services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

    healthcheck:
      test: kafka-broker-api-versions.sh --bootstrap-server localhost:9096 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - kafka:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=events

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=username
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=default
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  api:
    build:
      context: .
      dockerfile: src/event_api/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      kafka:
        condition: service_healthy
    command: bash run.sh

  sender:
    build:
      context: .
      dockerfile: src/event_sender/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      api:
        condition: service_healthy
    command: bash run.sh

volumes:
  kafka:
  clickhouse_data: