global:
  scrape_interval: 1s  # частота снятия метрик
remote_write:
  - url: "http://prometheus:9090/api/v1/write"
scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
  - job_name: "kafka"
    metrics_path: /metrics
    static_configs:
      - targets: [ "kafka-exporter:9308" ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
